apiVersion: v1
kind: Service
metadata:
  name: code-challenge-helloworld
  labels:
    app: code-challenge-helloworld
spec:
  ports:
  - name: http
    port: 3333
  selector:
    app: code-challenge-helloworld

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcode-challenge-elloworld
spec:
  selector:
    matchLabels:
      app: code-challenge-helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: code-challenge-helloworld
    spec:
      containers:
        - image: noravth/code-challenge-hello-world-python-image
          name: code-challenge-helloworld
          ports:
          - containerPort: 3333
